- go.mod
- go.sum
- main.go
* Update dependencies to release v0.3.0
* Do not print config
> update dependencies, do not print conf

- config.example.json
- go.mod
- go.sum
- lib/repo_query_nonce.go
- usecase/spawn_actor_processes.go
* Update chain dependencies
* Bugfix: Reputer to get earlier nonce, not latest nonce
> Update dependencies + reputer nonce fix

- CHANGELOG.md
- lib/factory_config.go
Honor `SubmitTx` from config. If set to false, it would still send tx if other configs are proper.
> SubmitTx false - still sends tx

- config.cdk.json.template
Adding a template file for CDK to use to populate variables into the JSON config automatically.
- No tests needed. Just a config file that is going to be find->replaced through from a command line.
- I don't think docs are needed as this will happen automated in the background when doing this through the aws-node-runners repo
> CDK config template file

- CHANGELOG.md
- lib/repo_tx_registration.go
Exit registration in the case of misssing params.
ORA-2149 Nil Pointer being passed to tx registration
> Fix covering nil pointer when params are not available

- CHANGELOG.md
- lib/factory_config.go
PROTO-2226
Graceful error handling on configuration/registration errors.
> Fix account not being ready, better error handling, no nilp

- lib/repo_tx_registration.go
> rm how already being registered blocks stake update; ensure stake idempotency

- README.md
- lib/domain_config.go
- lib/factory_config.go
Hello
While looking through your docs I found and fixed several spelling issues.
> docs: fix spelling issues

- config.example.json
- go.mod
- go.sum
Update go dependencies to the latest chain version, 0.4.0. 
Also increase loopSeconds to 10 on inferer.
Trivial, not needed
> Update go dependencies, increase loopSeconds on inferer

- CHANGELOG.md
- lib/repo_tx_utils.go
Do not retry if in passive set.
> Passive set: do not retry if score already found

- README.md
> Update description in prometheus section

- CHANGELOG.md
- usecase/spawn_actor_processes.go
Improve logs, removing misleading logs, aligning worker/reputer logs.
> improve logs

- CHANGELOG.md
- usecase/spawn_actor_processes.go
Chain nodes are hit repeteadly to get the open nonces.
If any of these requests fail, the loglevel is Error. 
It is an error on server side, but it will be retried normally, so the severity can be reduced to a warning, adding a potential explanation tip.
PROTO-2265 
> Reduce severity of node nonce error

- CHANGELOG.md
- usecase/spawn_actor_processes.go
* Reduce severity of node nonce error
* add to changelog
Release additions merged to dev too.
> gitflow - merge release to dev prior to merge to main

- CHANGELOG.md
- README.md
- config.example.json
- go.mod
- go.sum
- lib/domain_config.go
- lib/factory_config.go
- lib/repo_query_block.go
- lib/repo_query_nonce.go
- lib/repo_query_registration.go
- lib/repo_query_stake.go
- lib/repo_tx_registration.go
- lib/repo_tx_utils.go
- main.go
- usecase/build_commit_reputer_payload.go
- usecase/build_commit_worker_payload.go
- usecase/spawn_actor_processes.go
> Main 2 dev

- go.mod
- go.sum
Temporary update of dependencies to a `v0.6.0` commit. 
Chain `v0.6.0` is in development currently, so these are not the definitive dependencies for offchain release `v0.5.0`, but this allows this release code to be tested against a `v0.6.0` chain.
When chain is ready, update dependencies again prior to release.
> Update dependencies to a temporary 0.6.0 in-progress commit

- CHANGELOG.md
- README.md
- lib/factory_config.go
- lib/repo_tx_utils.go
* Account Sequence Mismatch handling - explicitly set the expected sequence number
* Refactored error handling
* Separation on error handling on creation of tx (which could already get the acct mismatch error) and broadcast of tx.
> Acct Seq Mismatch using expected num + refactor error handling

- CHANGELOG.md
Changelog adjustment for release `v0.5.1`.
N/A - changelog for release
> v0.5.1 release changelog setting

- CHANGELOG.md
- lib/repo_tx_registration.go
- lib/repo_tx_utils.go
- usecase/build_commit_reputer_payload.go
- usecase/build_commit_worker_payload.go
- usecase/spawn_actor_processes.go
* Allow to set timeoutHeight in `SendDataWithRetry`. 
* Worker and Reputer sending TimeoutHeight to be the block at the end of the submission window in each case.
> Set TimeoutHeight on worker/reputer tx

- CHANGELOG.md
- README.md
- config.cdk.json.template
- config.example.json
- lib/domain_config.go
- lib/repo_query_balance.go
- lib/repo_query_block.go
- lib/repo_query_nonce.go
- lib/repo_query_registration.go
- lib/repo_query_stake.go
- lib/repo_query_topic.go
- lib/repo_query_utils.go
- lib/repo_tx_registration.go
- lib/repo_tx_utils.go
- logger.go
- usecase/build_commit_reputer_payload.go
- usecase/build_commit_worker_payload.go
- usecase/build_commit_worker_payload_test.go
- usecase/spawn_actor_processes.go
- usecase/spawn_actor_processes_test.go
- usecase/usecase_suite.go
Smart window detection, reducing the need queries for open nonces
* Refactored mechanism to use same for workers and reputers via interface.
* Fair offset calculation within window
* Configurable and generic `QueryDataWithRetry`, to further reduce the chance of missing an epoch
* Added parameters to control the mechanism, explained in README
Other fixes
* Account Sequence and Fees error mgmt is now robust - there's persistence of errors.
* Loglevels - adding Trace.
* Use of retries in all queries for robustness.
* More robust registration and staking, using confirmation of registration and stake before going forward (otherwise the actor will just get its tx continuously rejected)
* Fix panic when account on the keyring suddenly vanishes (eg cases of key removal or rebuilding keyring)
* …
> WIP Smart worker check for open window + persistent error mgmt

- CHANGELOG.md
- adapter/api/worker-reputer/main.go
Reduce log severity on adapter logging
> Adjust adapter log levels

- CHANGELOG.md
- adapter/api/source/README.md
- adapter/api/source/main.py
Fix code scanning alert 
Restructure local testing adapter app's README
> Remove scanning alert on example app

- .github/workflows/test.yml
- CHANGELOG.md
> Unit tests on CI/CD

- lib/repo_query_actor_whitelist.go
- lib/repo_query_balance.go
- lib/repo_query_block.go
- lib/repo_query_nonce.go
- lib/repo_query_registration.go
- lib/repo_query_stake.go
- lib/repo_query_topic.go
- lib/repo_query_utils.go
- lib/repo_tx_registration.go
- lib/repo_tx_utils.go
- lib/utils.go
- main.go
- usecase/build_commit_reputer_payload.go
- usecase/build_commit_worker_payload.go
- usecase/spawn_actor_processes.go
- usecase/utils.go
All contexts was "mocked" with Background(), which is not the best approach. Running goroutines are not controlled by spawner.
I've added context handling, started from the very beginning of running offchain node.
Additionally I've added graceful shutdown to handle termination correctly
> Context handling

- CHANGELOG.md
- lib/repo_query_actor_whitelist.go
* Uses `CanSubmitPayload` methods instead of checking whitelists. Initial impl overlooked such methods.
> use canSubmitXPayload methods

- CHANGELOG.md
- go.mod
- go.sum
> Update chain dependencies to v0.7.0

- docker-compose.yaml
> remove vmagent from offchain node

- CHANGELOG.md
- lib/factory_config.go
> Customize rpc client configurations

- gas_and_fees.md
> Fix md formatting in gas_and_fees

- README.md
fix simple corrections:
environemnt -> environment  
bumdle -> bundle  
commiting -> committing  
the both the -> both the  
configered -> configured
> fix typo Update README.md

- CHANGELOG.md
- go.mod
- go.sum
Update v0.12.0 chain dependencies.
> Update v0.12.0 chain dependencies

- CHANGELOG.md
- README.md
- lib/connection_manager.go
- lib/domain_config.go
- lib/errors.go
- metrics/constant.go
- usecase/build_commit_reputer_payload.go
- usecase/build_commit_worker_payload.go
- usecase/repo_tx_registration.go
* Add error metrics
* Remove unused metrics
* Fix handling of `worker/reputer nonce window not available` errors if coming without error code from chain.
> Add error-level metrics, remove unused metrics
